### ISSUE TITLE
Tailwind css variables not working 

### ISSUE THREAD

**Issue by AhmedTirhmert** [dianprata/nuxt-shadcn-dashboard#2]
As shown in the setup below after following the docs for customizing the template 

![image](https://github.com/user-attachments/assets/59eb80e5-538a-40b8-ac5a-07bb3fba98b1)

- [x] created the `globals.css` file for custom variables/colors
- [x] updated `components.json` path to the `globals.css` that contains the variables 
- [x] extended the tailwind CSS colors to include the added color 

But when using the `warning` color in the `index.vue` file it doesn't work 

PS: I also tried to extend the tailwind config without using variables and yet it still doesn't work

![image](https://github.com/user-attachments/assets/07ba006d-44e4-4886-9536-1571a1e81ae3)

**Comment by dianprata** [comment]
i am use unocss, so you have to custom your colors in uno.config.ts.
add this code to uno.config.ts, but in unocss for custom colors in dark and light mode, you have to add new preset.
`theme: {
    colors: {
      'warning': 'hsl(38 92% 50%)',
      'warning-foreground': 'hsl(48 96% 89%)',
    },
  },`

ref: [https://github.com/unocss/unocss/issues/1390](https://github.com/unocss/unocss/issues/1390)
